import dynamic from "next/dynamic";
import Navbar from "@/my_components/Navbar/Navbar";
import { cookies, headers } from "next/headers";
import axios from "axios";
import DashboardProvider from "@/my_components/providers/DashboardProvider";

const RightSideNavbar = dynamic(
  () => import("@/my_components/Navbar/RightSideNavbar")
);

export const metadata = {
  title: "XYZ | Dashboard",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let dashboardInfo: any;
  try {
    const host = headers().get("host");
    const cookieStore = cookies();
    const access_token = cookieStore.get("access_token");
    const { data } = await axios.get(`http://${host}/api/v1/dashboard`, {
      headers: {
        Cookie: `${access_token?.name}=${access_token?.value}`,
      },
    });
    if (data.success) {
      dashboardInfo = data.data;
    }
  } catch (err: any) {
    console.log(err);
  }

  if (!dashboardInfo) {
    return null;
  }

  return (
    <DashboardProvider
      recentJoined={dashboardInfo.PeopleCount}
      Events={dashboardInfo.Events}
      UserInfo={{
        name: dashboardInfo.name,
        imageUrl: dashboardInfo.image,
        role: dashboardInfo.role,
      }}
      PaymentAmount={dashboardInfo.Payment}
    >
      {dashboardInfo.role === "admin" && <RightSideNavbar />}
      <Navbar
        userInfo={{
          name: dashboardInfo.name,
          imageUrl: dashboardInfo.image,
          role: dashboardInfo.role,
        }}
      />
      <div className="px-2 md:px-4 max-w-7xl mx-auto min-h-dvh">{children}</div>
    </DashboardProvider>
  );
}
