import Navbar from "@/my_components/Navbar/Navbar";
import RightSideNavbar from "@/my_components/Navbar/RightSideNavbar";

export const metadata = {
  title: "XYZ | Dashboard",
  description: "Generated by Next.js",
};

interface UserInfoValue {
  name: string;
  imageUrl: string;
  role: string;
}
const UserInfo: UserInfoValue = {
  name: "Abhradip Paul",
  imageUrl: "",
  role: "Admin",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <RightSideNavbar />
        <Navbar userInfo={UserInfo} />
        <div className="px-4 max-w-7xl mx-auto">{children}</div>
      </body>
    </html>
  );
}
